version: '3.8'

services:
  onixwiki:
    image: exoticonix/onixwiki:latest
    restart: always
    depends_on:
      - mysql
    environment:
      APP_NAME: OnixWiki
      APP_ENV: production
      APP_KEY: base64:ZpFPW8y/JLBQSBDGw7djTJsKApSc5k79axBWy1aq6ps=
      APP_DEBUG: false
      APP_URL: http://localhost
      FORCE_HTTPS: "false"

      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US

      APP_MAINTENANCE_DRIVER: file
      # APP_MAINTENANCE_STORE: database

      PHP_CLI_SERVER_WORKERS: "4"

      BCRYPT_ROUNDS: "12"

      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: warning

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: onixwiki
      DB_USERNAME: onixwiki
      DB_PASSWORD: onixwiki_password

      SESSION_DRIVER: database
      SESSION_LIFETIME: "120"
      SESSION_ENCRYPT: "false"
      SESSION_PATH: /
      SESSION_DOMAIN: null

      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      SCOUT_QUEUE: "false"
      CACHE_STORE: database
      # CACHE_PREFIX:

      MEMCACHED_HOST: 127.0.0.1

      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: "6379"

      MAIL_MAILER: smtp
      MAIL_SCHEME: null
      MAIL_HOST: smtp.yourmail.com
      MAIL_PORT: "587"
      MAIL_USERNAME: your_mail_user
      MAIL_PASSWORD: your_mail_pass
      MAIL_FROM_ADDRESS: "no-reply@yourdomain.com"
      MAIL_FROM_NAME: OnixWiki
      MAIL_ENCRYPTION: tls

      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ""
      AWS_USE_PATH_STYLE_ENDPOINT: "false"

      VITE_APP_NAME: OnixWiki

    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: onixwiki
      MYSQL_USER: onixwiki
      MYSQL_PASSWORD: onixwiki_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
