services:
  onixwiki:
    image: exoticonix/onixwiki:latest
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
